data MONEYBALL_TEST_PREP;
	set mydata.MONEYBALL_TEST;
	TEAM_BATTING_SO_IMP=TEAM_BATTING_SO;
	TEAM_BATTING_SO_IMP_IND=0;
	TEAM_BASERUN_SB_IMP=TEAM_BASERUN_SB;
	TEAM_BASERUN_SB_IMP_IND=0;
	TEAM_BASERUN_CS_IMP_IND=0;
	TEAM_FIELDING_DP_IMP_IND=0;
	TEAM_PITCHING_SO_IMP_IND=0;
	TEAM_OBP_TIMESONBASE = TEAM_BATTING_H + TEAM_BATTING_BB;
	IF MISSING(TEAM_BATTING_HBP) THEN DO;
			TEAM_BATTING_HBP_IMP_IND=1;
			END;
	ELSE TEAM_BATTING_HBP_IMP_IND=0;
	IF MISSING(TEAM_FIELDING_DP) THEN DO;
			TEAM_FIELDING_DP_IMP=149;
			TEAM_FIELDING_DP_IMP_IND=1;
			END;
	ELSE TEAM_FIELDING_DP_IMP=TEAM_FIELDING_DP;
	if missing (TEAM_BATTING_SO) and (TEAM_PITCHING_BB > 280 and TEAM_PITCHING_BB <= 500) and 
		(TEAM_PITCHING_H >= 1137 and TEAM_PITCHING_H <= 1518) and (TEAM_PITCHING_HR >= 0 and TEAM_PITCHING_HR <= 107) then
			do;
			TEAM_BATTING_SO_IMP=746.1;
			TEAM_BATTING_SO_IMP_IND=1;
		END;
	else if missing (TEAM_BATTING_SO) and (TEAM_PITCHING_BB > 280 and TEAM_PITCHING_BB <= 500) and 
		(TEAM_PITCHING_H > 1518 and TEAM_PITCHING_H <= 2050) and (TEAM_PITCHING_HR >= 0 and TEAM_PITCHING_HR <= 107) then
			do;
			TEAM_BATTING_SO_IMP=520.7;
			TEAM_BATTING_SO_IMP_IND=1;
		END;
	else if missing (TEAM_BATTING_SO) and (TEAM_PITCHING_BB > 500 and TEAM_PITCHING_BB <= 820) and 
		(TEAM_PITCHING_H >= 1137 and TEAM_PITCHING_H <= 1518) and (TEAM_PITCHING_HR >= 0 and TEAM_PITCHING_HR <= 107) then
			do;
			TEAM_BATTING_SO_IMP=721.9;
			TEAM_BATTING_SO_IMP_IND=1;
		END;
	else if missing (TEAM_BATTING_SO) and (TEAM_PITCHING_BB > 500 and TEAM_PITCHING_BB <= 820) and 
		(TEAM_PITCHING_H > 1518 and TEAM_PITCHING_H <= 2050) and (TEAM_PITCHING_HR >= 0 and TEAM_PITCHING_HR <= 107) then
			do;
			TEAM_BATTING_SO_IMP=518.9;
			TEAM_BATTING_SO_IMP_IND=1;
		END;
	IF MISSING(TEAM_BASERUN_CS) THEN DO;
			TEAM_BASERUN_CS_IMP=49;
			TEAM_BASERUN_CS_IMP_IND=1;
			END;
	ELSE TEAM_BASERUN_CS_IMP=TEAM_BASERUN_CS;
	if missing (TEAM_BASERUN_SB) and (TEAM_BASERUN_CS_IMP >= 0 and TEAM_BASERUN_CS_IMP <= 50) and 
		(TEAM_FIELDING_DP_IMP > 82 and TEAM_FIELDING_DP_IMP <= 154) then
			do;
			TEAM_BASERUN_SB_IMP=162.7;
			TEAM_BASERUN_SB_IMP_IND=1;
		END;
	else if missing (TEAM_BASERUN_SB) and (TEAM_BASERUN_CS_IMP >= 0 and TEAM_BASERUN_CS_IMP <= 50) and 
		(TEAM_FIELDING_DP_IMP >= 0 and TEAM_FIELDING_DP_IMP <= 82) then
			do;
			TEAM_BASERUN_SB_IMP=127.61;
			TEAM_BASERUN_SB_IMP_IND=1;
		END;
	IF MISSING(TEAM_PITCHING_SO) THEN DO;
			TEAM_PITCHING_SO_IMP=813.5;
			TEAM_PITCHING_SO_IMP_IND=1;
			END;
	ELSE TEAM_PITCHING_SO_IMP=TEAM_PITCHING_SO;
	
	TEAM_BATTING_1B = TEAM_BATTING_H - (TEAM_BATTING_2B + TEAM_BATTING_3B + TEAM_BATTING_HR);

	if TEAM_BATTING_HR=0 then log_TEAM_BATTING_HR=0;
	else log_TEAM_BATTING_HR=log(TEAM_BATTING_HR);
	
	if TEAM_BASERUN_SB_IMP=0 then log_TEAM_BASERUN_SB_IMP=0;
	else log_TEAM_BASERUN_SB_IMP=log(TEAM_BASERUN_SB_IMP);
	
	log_TEAM_FIELDING_E=log(TEAM_FIELDING_E);

	P_TARGET_WINS=119.75952 +
					(0.0375 * TEAM_BATTING_1B) +
					(0.17983 * TEAM_BATTING_3B) +
					(6.52573 * log_TEAM_BATTING_HR) +
					(0.05109 * TEAM_BATTING_BB) +
					(3.46861 * TEAM_BATTING_HBP_IMP_IND) +
					(-0.01324 * TEAM_BATTING_SO_IMP) +
					(0.07502 * TEAM_BASERUN_SB_IMP) +
					(35.73807 * TEAM_BASERUN_SB_IMP_IND) +
					(-0.08007 * TEAM_BASERUN_CS_IMP) +
					(3.86297 * TEAM_BASERUN_CS_IMP_IND) +
					(-23.88903 * log_TEAM_FIELDING_E) +
					(-0.1033 * TEAM_FIELDING_DP_IMP) +
					(-0.01239 * TEAM_PITCHING_BB) +
					(0.0013 * TEAM_PITCHING_H) +
					(8.4069 * TEAM_PITCHING_SO_IMP_IND);
	P_TARGET_WINS = round( P_TARGET_WINS, 1 );
run;


/*
proc print data=MONEYBALL_TEST_PREP;
var index p_target_wins;
run;
*/